### ISSUE TITLE
to_json 不支持int64_t uint64_t  等

### ISSUE THREAD

**Issue by lq277012525** [qicosmos/iguana#11]
```
#include "json.hpp"
#include "reflection.hpp"
struct ita
{
	int64_t b;
};
REFLECTION(ita,  b)
int main()
{
     ita f{1 };
     iguana::string_stream ss;
     iguana::json::to_json(ss, f);
     auto json_str = ss.str();
     std::cout << json_str << std::endl;
     return 0;
}
```
编译报错（vs2017）

**Comment by qicosmos** [comment]
你这个代码我测试没发现问题，你的编译报错信息是什么？贴出来看一下

**Comment by lq277012525** [comment]
iguana-master\iguana\json.hpp(207): warning C4018: “<”: 有符号/无符号不匹配
1>d:\iguana-master\iguana\detail\itoa.hpp(88): error C2027: 使用了未定义类型“dec_::UT<16,16>”
1>d:\iguana-master\iguana\detail\itoa.hpp(88): note: 参见“dec_::UT<16,16>”的声明
1>d:\iguana-master\iguana\detail\itoa.hpp(88): note: 参见对正在编译的 类 模板 实例化 "dec_::UT<16,8,dec_::MulInv<uint64_t,false,12379400392853802749,90>>" 的引用
1>d:\iguana-master\iguana\detail\itoa.hpp(88): note: 参见对正在编译的 类 模板 实例化 "dec_::UT<16,4,dec_::MulInv<uint32_t,false,3518437209,45>,dec_::MulInv<uint64_t,false,12379400392853802749,90>>" 的引用
1>d:\iguana-master\iguana\detail\itoa.hpp(88): note: 参见对正在编译的 类 模板 实例化 "dec_::UT<16,2,dec_::MulInv<uint16_t,true,41943,22>,dec_::MulInv<uint32_t,false,3518437209,45>,dec_::MulInv<uint64_t,false,12379400392853802749,90>>" 的引用
1>d:\iguana-master\iguana\detail\itoa.hpp(106): note: 参见对正在编译的 类 模板 实例化 "dec_::UT<16,1,dec_::MulInv<uint8_t,false,205,11>,dec_::MulInv<uint16_t,true,41943,22>,dec_::MulInv<uint32_t,false,3518437209,45>,dec_::MulInv<uint64_t,false,12379400392853802749,90>>" 的引用
1>d:\iguana-master\iguana\detail\itoa.hpp(195): note: 参见对正在编译的函数 模板 实例化“dec_::QR<8> dec_::split<8>(unsigned __int64)”的引用
1>d:\iguana-master\iguana\detail\itoa.hpp(256): note: 参见对正在编译的函数 模板 实例化“char *dec_::convert<dec_::Fwd>::itoa<unsigned __int64,8>(char *,UInt)”的引用
1>        with
1>        [
1>            UInt=unsigned __int64
1>        ]
1>d:\iguana-master\iguana\detail\itoa.hpp(256): note: 参见对正在编译的函数 模板 实例化“char *dec_::convert<dec_::Fwd>::itoa<unsigned __int64,8>(char *,UInt)”的引用
1>        with
1>        [
1>            UInt=unsigned __int64
1>        ]
1>d:\iguana-master\iguana\detail\itoa.hpp(265): note: 参见对正在编译的函数 模板 实例化“char *dec_::convert<dec_::Fwd>::itoa<I,8,0x0>(I,char *)”的引用
1>        with
1>        [
1>            I=int64_t
1>        ]
1>d:\iguana-master\iguana\detail\itoa.hpp(265): note: 参见对正在编译的函数 模板 实例化“char *dec_::convert<dec_::Fwd>::itoa<I,8,0x0>(I,char *)”的引用
1>        with
1>        [
1>            I=int64_t
1>        ]
1>d:\iguana-master\iguana\json.hpp(48): note: 参见对正在编译的函数 模板 实例化“char *itoa_fwd<T>(I,char *)”的引用
1>        with
1>        [
1>            T=int64_t,
1>            I=int64_t
1>        ]
1>d:\iguana-master\iguana\json.hpp(151): note: 参见对正在编译的函数 模板 实例化“void iguana::json::render_json_value<Stream,int64_t>(Stream &,T)”的引用
1>        with
1>        [
1>            Stream=iguana::string_stream,
1>            T=int64_t
1>        ]
1>d:\iguana-master\iguana\reflection.hpp(457): note: 参见对正在编译的函数 模板 实例化“void iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>::operator ()<int64_t>(const int64_t &,::size_t,bool) const”的引用
1>d:\iguana-master\iguana\reflection.hpp(487): note: 参见对正在编译的函数 模板 实例化“void iguana::apply_value<0,_Ty,iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,int64_t&>(F &&,F1 &&,T,bool)”的引用
1>        with
1>        [
1>            _Ty=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F1=iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,
1>            T=int64_t &
1>        ]
1>d:\iguana-master\iguana\reflection.hpp(503): note: 参见对正在编译的函数 模板 实例化“void iguana::apply<_Ty,iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,ita&,__int64ita::* ,0,>(F &&,F1 &&,T,std::tuple<__int64 ita::* > &&,std::integer_sequence<unsigned int,0>)”的引用
1>        with
1>        [
1>            _Ty=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F1=iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,
1>            T=ita &
1>        ]
1>d:\iguana-master\iguana\reflection.hpp(518): note: 参见对正在编译的函数 模板 实例化“void iguana::for_each_impl<0,_Ty,iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,ita&>(F &&,F1 &&,T,bool)”的引用
1>        with
1>        [
1>            _Ty=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F1=iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,
1>            T=ita &
1>        ]
1>d:\iguana-master\iguana\json.hpp(160): note: 参见对正在编译的函数 模板 实例化“void iguana::for_each<ita&,iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>>(T,F &&,F1 &&)”的引用
1>        with
1>        [
1>            T=ita &,
1>            F=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F1=iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>
1>        ]
1>c:\users\houduan\documents\visual studio 2017\projects\testref\testref\testref.cpp(17): note: 参见对正在编译的函数 模板 实例化“void iguana::json::to_json<iguana::string_stream,ita&>(Stream &,T)”的引用
1>        with
1>        [
1>            Stream=iguana::string_stream,
1>            T=ita &
1>        ]
1>d:\iguana-master\iguana\detail\itoa.hpp(106): error C2938: “U<16>”: 未能使别名模板专用化
1>d:\iguana-master\iguana\detail\itoa.hpp(106): error C2061: 语法错误: 标识符“u”

**Comment by lq277012525** [comment]
@qicosmos 错误提示如下 有点长
iguana-master\iguana\json.hpp(207): warning C4018: “<”: 有符号/无符号不匹配
1>d:\iguana-master\iguana\detail\itoa.hpp(88): error C2027: 使用了未定义类型“dec_::UT<16,16>”
1>d:\iguana-master\iguana\detail\itoa.hpp(88): note: 参见“dec_::UT<16,16>”的声明
1>d:\iguana-master\iguana\detail\itoa.hpp(88): note: 参见对正在编译的 类 模板 实例化 "dec_::UT<16,8,dec_::MulInv<uint64_t,false,12379400392853802749,90>>" 的引用
1>d:\iguana-master\iguana\detail\itoa.hpp(88): note: 参见对正在编译的 类 模板 实例化 "dec_::UT<16,4,dec_::MulInv<uint32_t,false,3518437209,45>,dec_::MulInv<uint64_t,false,12379400392853802749,90>>" 的引用
1>d:\iguana-master\iguana\detail\itoa.hpp(88): note: 参见对正在编译的 类 模板 实例化 "dec_::UT<16,2,dec_::MulInv<uint16_t,true,41943,22>,dec_::MulInv<uint32_t,false,3518437209,45>,dec_::MulInv<uint64_t,false,12379400392853802749,90>>" 的引用
1>d:\iguana-master\iguana\detail\itoa.hpp(106): note: 参见对正在编译的 类 模板 实例化 "dec_::UT<16,1,dec_::MulInv<uint8_t,false,205,11>,dec_::MulInv<uint16_t,true,41943,22>,dec_::MulInv<uint32_t,false,3518437209,45>,dec_::MulInv<uint64_t,false,12379400392853802749,90>>" 的引用
1>d:\iguana-master\iguana\detail\itoa.hpp(195): note: 参见对正在编译的函数 模板 实例化“dec_::QR<8> dec_::split<8>(unsigned __int64)”的引用
1>d:\iguana-master\iguana\detail\itoa.hpp(256): note: 参见对正在编译的函数 模板 实例化“char *dec_::convert<dec_::Fwd>::itoa<unsigned __int64,8>(char *,UInt)”的引用
1>        with
1>        [
1>            UInt=unsigned __int64
1>        ]
1>d:\iguana-master\iguana\detail\itoa.hpp(256): note: 参见对正在编译的函数 模板 实例化“char *dec_::convert<dec_::Fwd>::itoa<unsigned __int64,8>(char *,UInt)”的引用
1>        with
1>        [
1>            UInt=unsigned __int64
1>        ]
1>d:\iguana-master\iguana\detail\itoa.hpp(265): note: 参见对正在编译的函数 模板 实例化“char *dec_::convert<dec_::Fwd>::itoa<I,8,0x0>(I,char *)”的引用
1>        with
1>        [
1>            I=int64_t
1>        ]
1>d:\iguana-master\iguana\detail\itoa.hpp(265): note: 参见对正在编译的函数 模板 实例化“char *dec_::convert<dec_::Fwd>::itoa<I,8,0x0>(I,char *)”的引用
1>        with
1>        [
1>            I=int64_t
1>        ]
1>d:\iguana-master\iguana\json.hpp(48): note: 参见对正在编译的函数 模板 实例化“char *itoa_fwd<T>(I,char *)”的引用
1>        with
1>        [
1>            T=int64_t,
1>            I=int64_t
1>        ]
1>d:\iguana-master\iguana\json.hpp(151): note: 参见对正在编译的函数 模板 实例化“void iguana::json::render_json_value<Stream,int64_t>(Stream &,T)”的引用
1>        with
1>        [
1>            Stream=iguana::string_stream,
1>            T=int64_t
1>        ]
1>d:\iguana-master\iguana\reflection.hpp(457): note: 参见对正在编译的函数 模板 实例化“void iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>::operator ()<int64_t>(const int64_t &,::size_t,bool) const”的引用
1>d:\iguana-master\iguana\reflection.hpp(487): note: 参见对正在编译的函数 模板 实例化“void iguana::apply_value<0,_Ty,iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,int64_t&>(F &&,F1 &&,T,bool)”的引用
1>        with
1>        [
1>            _Ty=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F1=iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,
1>            T=int64_t &
1>        ]
1>d:\iguana-master\iguana\reflection.hpp(503): note: 参见对正在编译的函数 模板 实例化“void iguana::apply<_Ty,iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,ita&,__int64ita::* ,0,>(F &&,F1 &&,T,std::tuple<__int64 ita::* > &&,std::integer_sequence<unsigned int,0>)”的引用
1>        with
1>        [
1>            _Ty=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F1=iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,
1>            T=ita &
1>        ]
1>d:\iguana-master\iguana\reflection.hpp(518): note: 参见对正在编译的函数 模板 实例化“void iguana::for_each_impl<0,_Ty,iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,ita&>(F &&,F1 &&,T,bool)”的引用
1>        with
1>        [
1>            _Ty=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F1=iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>,
1>            T=ita &
1>        ]
1>d:\iguana-master\iguana\json.hpp(160): note: 参见对正在编译的函数 模板 实例化“void iguana::for_each<ita&,iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>>(T,F &&,F1 &&)”的引用
1>        with
1>        [
1>            T=ita &,
1>            F=iguana::json::to_json::<lambda_ad720a1f22f173647e14027b8e8fb936>,
1>            F1=iguana::json::to_json::<lambda_5927dd7ed8bbfc3759265bb06e31c3ec>
1>        ]
1>c:\users\houduan\documents\visual studio 2017\projects\testref\testref\testref.cpp(17): note: 参见对正在编译的函数 模板 实例化“void iguana::json::to_json<iguana::string_stream,ita&>(Stream &,T)”的引用
1>        with
1>        [
1>            Stream=iguana::string_stream,
1>            T=ita &
1>        ]
1>d:\iguana-master\iguana\detail\itoa.hpp(106): error C2938: “U<16>”: 未能使别名模板专用化
1>d:\iguana-master\iguana\detail\itoa.hpp(106): error C2061: 语法错误: 标识符“u”

**Comment by shfxxer** [comment]
同样， int64_t time_t 数据类型出错

struct FileInfo
{
	int64_t filesize;
	time_t ModifyTime;
};


警告	C4018	“<”: 有符号/无符号不匹配	Test	d:\libs\iguana\iguana\json.hpp	207	
错误	C2027	使用了未定义类型“dec_::UT<16,16>”	Test	d:\libs\iguana\iguana\detail\itoa.hpp	88	
错误	C2938	“U<16>”: 未能使别名模板专用化	Test	d:\libs\iguana\iguana\detail\itoa.hpp	106	
错误	C2061	语法错误: 标识符“u”	Test	d:\libs\iguana\iguana\detail\itoa.hpp	106	

环境vs2015 update3+windows 7

**Comment by shfxxer** [comment]
顺手测了一下int64_t time_t在xml下的表现，同样不行

错误	C2665	“iguana::xml::render_xml_value”: 2 个重载中没有一个可以转换所有参数类型	Test	d:\libs\iguana\iguana\xml.hpp	324	

环境vs2015 update3+boost 1.63.0

**Comment by qicosmos** [comment]
@shfxxer 好的，谢谢指出问题，我抽空把bug解决掉。

**Comment by YiShuiHanFeng** [comment]
size_t类型也是一样的问题

使用了未定义类型“dec_::UT<16,16>”
iguana\detail\itoa.hpp	88

**Comment by qicosmos** [comment]
@YiShuiHanFeng 好，谢谢指出，我尽量这周修复bug。

**Comment by qicosmos** [comment]
@lq277012525 @shfxxer @YiShuiHanFeng 
现在支持了int64_t, uint64_t, size_t, 请你们验证一下。

**Comment by lq277012525** [comment]
我反序列化 uint64_t ，int64_t 出现错误的结果。to_json 结果正确 ，from_json 结果不正确。！！

**Comment by lq277012525** [comment]
我反序列化 uint64_t ，int64_t ，字段 出现错误的结果，其他字段结果都正确。to_json 结果正确 ，from_json 结果不正确。！！

**Comment by qicosmos** [comment]
@lq277012525 能把测试代码发一下吗？

**Comment by lq277012525** [comment]
`
struct MyStruct
{
	uint64_t a;
};
REFLECTION(MyStruct, a);
int main()
{
	MyStruct p = {  5566777755311 };
	iguana::string_stream ss;
	iguana::json::to_json(ss, p);
	auto json_str = ss.str();
	std::cout << json_str << std::endl;
	MyStruct p2;
	iguana::json::from_json(p2, json_str.data(), json_str.length());
	std::cout << p2.a << std::endl;
	return 0;
}
`
vs2017 环境  输出 p2.a=500139695  超过 UINT32_MAX 就会出错。from_json后的值会 翻转。 
如 4294967296( UINT32_MAX +1)  from_json后的值=0。

**Comment by qicosmos** [comment]
@lq277012525 
bug已经修复，之前from_json时转换为int了，现在可以了，请验证一下，多测试测试，谢谢。

**Comment by shfxxer** [comment]
int64_t, uint64_t, size_t,uintmax_t,uint_least64_t,uint64_t序列化成功。感谢作者的贡献。

环境 windows 7 sp1 7601+visual studio 2015 sp3 x86+x64。
