### ISSUE TITLE
建议用 nlohmann/json 解析和序列化json

### ISSUE THREAD

**Issue by mlkt** [qicosmos/iguana#14]
用这个库来解析和序列化比较好吧？
毕竟这个专精于json，功能更多更强大，支持的功能更多，比起自己来解析应该更稳定一些
https://github.com/nlohmann/json

**Comment by qicosmos** [comment]
其实只要关注反序列化解析json串就行了，序列化部分比较简单。
我使用的反序列化json串的代码用的是ajson的reader，性能很好。
你可以比较一下iguana和你列举的json库的性能，看那个序列化和反序列化的性能更好，初步估计iguana应该比你列举的json库要快几倍o(∩_∩)o

**Comment by famik** [comment]
> 其实只要关注反序列化解析json串就行了，序列化部分比较简单。
> 我使用的反序列化json串的代码用的是ajson的reader，性能很好。
> 你可以比较一下iguana和你列举的json库的性能，看哪个序列化和反序列化的性能更好，初步估计iguana应该比你列举的json库要快几倍o(∩_∩)o

为什么不用rapidjson？rapidjson不是更快吗？之前Kapok都是用rapidjson的

**Comment by qicosmos** [comment]
> > 其实只要关注反序列化解析json串就行了，序列化部分比较简单。
> > 我使用的反序列化json串的代码用的是ajson的reader，性能很好。
> > 你可以比较一下iguana和你列举的json库的性能，看哪个序列化和反序列化的性能更好，初步估计iguana应该比你列举的json库要快几倍o(∩_∩)o
> 
> 为什么不用rapidjson？rapidjson不是更快吗？之前Kapok都是用rapidjson的

恰恰相反，不用rapidjson是因为它比较慢，接口不好用是另外一个原因。
