### ISSUE TITLE
解析问题

### ISSUE THREAD

**Issue by xiaonaiquan** [qicosmos/iguana#157]
json字符串里面带有\n ，from_json之后把“\”去掉了
例子：
std::string a = "{"vmid":"aaaaa","vvfile":"[virt-viewer]\ntype=spice\nhost=10.241.62.2\n"}";
iguana::from_json(xxx, a.data(), a.length());
xxx.a = "[virt-viewer]ntype=spicenhost=10.241.62.2n"

**Comment by bbbgan** [comment]
感谢您提出的问题，已经在最新的pr中修复！您可以在example中自行添加以下代码进行测试

`struct issue_t {
  std::string vmid;
  std::string vvfile;
};
REFLECTION(issue_t, vmid, vvfile);

void test_issue() {
  std::string str ="{\"vmid\" : \"aaaaa\", \"vvfile\" : \"[virt-viewer]\ntype=spice\nhost=10.241.62.2\n\"}";
  issue_t iss;
  iguana::from_json(iss, str.data(), str.length());
  assert(iss.vvfile == "[virt-viewer]\ntype=spice\nhost=10.241.62.2\n");
  std::cout << iss.vmid << "\n" << iss.vvfile << "\n";
}
运行结果如下：
aaaaa
[virt-viewer]
type=spice
host=10.241.62.2

**Comment by qicosmos** [comment]
https://github.com/qicosmos/iguana/pull/158
在这个pr里修复了这个问题

**Comment by bbbgan** [comment]
由于[158](https://github.com/qicosmos/iguana/pull/158)的处理不太妥当，已经在最新的pr中重新修复了

**Comment by qicosmos** [comment]
已经合并了，更新master即可。

**Comment by xiaonaiquan** [comment]
辛苦大佬们，已修复
