### ISSUE TITLE
是否可以为枚举定义字符串值？比如将struct中的enum在json序列化中翻译为string

### ISSUE THREAD

**Issue by Yhaiyang** [qicosmos/iguana#184]

**Comment by bbbgan** [comment]
目前只是简单把enum序列化成数字，

**Comment by qicosmos** [comment]
可以做，晚点有时间了支持一下。

**Comment by bbbgan** [comment]
已经支持了将enum处理成字符串类型， 使用方法：
https://github.com/qicosmos/iguana#how-to-solve-the-problem-of-unicode-path-in-a-json-file

**Comment by qicosmos** [comment]
已经支持了吧，你把例子和文档链接发出来吧 @bbbgan

**Comment by bbbgan** [comment]
已经支持了将枚举处理成字符串的形式，默认还是数字的形式：下面是文档：
https://github.com/qicosmos/iguana#how-to-handle-the-enum-type-as-strings
下面是json的示例代码，yaml、xml类似：
https://github.com/qicosmos/iguana/blob/37c363e565dcec5b42166884647b6a705cd7da99/test/unit_test.cpp#L215-L279
