### ISSUE TITLE
最新是支持c++20,可以自定义支持c++17?

### ISSUE THREAD

**Issue by sonygod** [qicosmos/iguana#186]
最新是支持c++20,可以自定义支持c++17?

因为虚幻引擎当前只是支持c++17,所以问问有没有自定义的宏支持c++17

**Comment by bbbgan** [comment]
暂不支持，不过即将支持（大约一个月）

**Comment by bbbgan** [comment]
> 最新是支持c++20,可以自定义支持c++17?
> 
> 因为虚幻引擎当前只是支持c++17,所以问问有没有自定义的宏支持c++17

json已经支持了17！

**Comment by obqrn** [comment]
预计啥时候全面支持c++17呀？

**Comment by bbbgan** [comment]
> 预计啥时候全面支持c++17呀？

这2周吧，你一般用什么库

**Comment by obqrn** [comment]
json和yaml

**Comment by bbbgan** [comment]
已经全面支持了C++17！

**Comment by sonygod** [comment]
谢谢，有空我结合UE5综合测试再反馈
