### ISSUE TITLE
error C7571: “iguana::char_t”: 已初始化变量模板

### ISSUE THREAD

**Issue by obqrn** [qicosmos/iguana#206]
vs2022 cmake环境
yaml正常
引用#include "ylt/struct_json/json_reader.h"
#include "ylt/struct_json/json_writer.h"
后编译报错：error C7571: “iguana::char_t”: 已初始化变量模板

**Comment by bbbgan** [comment]
是包含头文件就报错吗？

**Comment by bbbgan** [comment]
可能是因为yaml和json一起有冲突？我这周末支持yaml17的时候顺便解决一下冲突。

**Comment by bbbgan** [comment]
我复现不出来，能详细一点吗？应该和 iguana::char_t 有关系！你同时使用了yaml和json吗

**Comment by obqrn** [comment]
是的，不过看起来解决了
