### ISSUE TITLE
怎么利用reflection17.hpp实现同名字段拷贝？

### ISSUE THREAD

**Issue by mlkt** [qicosmos/iguana#21]
struct AAA{
  int a;
  string b;
  int c;
};

struct BBB{
   string b;
  int c;
  int d;
};

AAA a;
BBB b;

a.b="aaa";
a.c=123;

b.b ="bbb";
b.d=754;

func(b, a);

func()执行完后 b.b为"aaa" ，b.c为123 ，b.d不变仍为754

**Comment by qicosmos** [comment]
没看懂你的意思，能说详细一些吗？

**Comment by mlkt** [comment]
额，上面我写的有点问题，我修改一下

就是两个不同的struct或者class 他们有相同名称、相同类型（或可互相转换）的字段
想用你这个自动反射实现类似这样一个函数（只是举个例子，实际如果可以做成重载赋值或者类型转换运算符更好）：
void func(BBB& b, AAA& a){
  b.b = a.b;
  b.c = a.c;
}
想知道能不能用你的这个反射可以自动找出它们名字相同的字段，然后拷贝，
这样就不用一句一句写赋值代码了

类似于java的DozerBeanMapper

**Comment by qicosmos** [comment]
同名的字段可能类型都不同，这样做有问题的。

**Comment by mlkt** [comment]
当然是可以互相赋值的才能这样搞，如果不能就编译报错

**Comment by qicosmos** [comment]
可以实现，挺奇怪的需求。
