### ISSUE TITLE
请支持一下std::set

### ISSUE THREAD

**Issue by Rendtime** [qicosmos/iguana#231]
现在还不支持这个，请支持一下，谢谢

**Comment by bbbgan** [comment]
好的，会在近期内尽快支持的！

**Comment by Rendtime** [comment]
开始使用map，感觉不够节省。set类型更节省一些，因为我只要key，现在改成vector了，查询的时候再转了一次。

**Comment by Rendtime** [comment]
暂时就这样，以后能支持set更好，总的来说还是非常nice
