### ISSUE TITLE
对于union目前有好的处理办法吗？

### ISSUE THREAD

**Issue by luotian1957** [qicosmos/iguana#244]
typedef struct
{
    union
    {
        int min;         ///< Minimum value.
        float  minFloat;    ///< Minimum value in the float.
    };
    union
    {
        int max;         ///< Maximum value.
        float  maxFloat;    ///< Maximum value in the float.
    };
} StatsRange;

REFLECTION(StatsRange, min, minFloat, max, maxFloat);

    StatsRange test = {};
    test.maxFloat = 5.6;
    test.min = 5;
实际输出：
   "StatsRange" : [
      {
         "max" : 1085485875,
         "maxFloat" : 5.5999999999999996,
         "min" : 5,
         "minFloat" : 7e-45
      }
   ]

期望输出：
   "StatsRange" : [
      {
         "maxFloat" : 5.5999999999999996,
         "min" : 5
      }
   ]

**Comment by qicosmos** [comment]
还没支持union，主要问题是序列化反序列化的时候无法知道到底哪一个是active member，访问非active的member是UB 行为

**Comment by qicosmos** [comment]
可以把union改成std::variant

**Comment by luotian1957** [comment]
主要结构体是三方的，不太好改。  我尝试使用std::variant单独保存这种的吧，多谢
