### ISSUE TITLE
json解析不支持REFLECTION_ALIAS?

### ISSUE THREAD

**Issue by zyx199518** [qicosmos/iguana#270]
后续json是否支持成员变量别名映射解析?

**Comment by bbbgan** [comment]
json、xml、yaml都是支持别名映射的 ，见[文档](https://github.com/qicosmos/iguana/blob/master/lang/iguana%20%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.md#%E5%AD%97%E6%AE%B5%E5%88%AB%E5%90%8D)
