### ISSUE TITLE
struct_pb 不支持 std::array 类型

### ISSUE THREAD

**Issue by wangwenx190** [qicosmos/iguana#320]
结构体中包含std::array成员会导致编译错误，而且像`double[3]`这样的简单数组也没法编译，这个是不是pb天然的限制？有没有什么办法绕过呢

**Comment by wangwenx190** [comment]
不过这事有点怪，std::vector是能通过编译的，std::array难道不能当作一种特殊的定长vector？

**Comment by qicosmos** [comment]
protobuf 只有一个repeated类型，它就是和vector对应的，你把它array怎么对应呢？要考虑protobuf协议的限制，它没有对应的fixed reapeated的东西，不能乱加类型。

不是不能对应是要符合protobuf 协议，像json xml 都支持了array，因为它们确实是有实际的类型可以对应

**Comment by wangwenx190** [comment]
好的，明白了，也就是我自己这边可以把所有array都换成vector，其实效果都是一样的。感谢作者的回复。
