### ISSUE TITLE
当存在值为0的枚举时，转换到pb失败

### ISSUE THREAD

**Issue by wangwenx190** [qicosmos/iguana#324]
以下代码必现此bug：
```cpp
enum MyEnum { AA = 0 };
struct MyStruct {
  MyEnum myEnum = MyEnum::AA; 
  // 枚举后的所有内容都会被忽略，此处随便添加一些成员举例：
  bool myBool = false;
  int myInt = 0;
};
YLT_REFL(MyStruct, myEnum, myBool, myInt)

int main() {
  MyStruct myStruct{};
  std::string str{};
  iguana::to_pb(myStruct, str);
  return 0;
}
```
经过我的调试，只要枚举值为0，那么str始终是空的，无论后面有什么东西，但如果枚举值不是0，输出的内容就是对的。

**Comment by wangwenx190** [comment]
基于最新的release 1.0.6测试的

**Comment by wangwenx190** [comment]
我这边用了挺多各种各样的结构体的，结构体之间也有很多继承关系，但貌似只有涉及值为0的枚举时才会出现这个问题

**Comment by wangwenx190** [comment]
我测试了几种组合，明白问题在哪了。任何东西只要值是0，就会被完全省略掉，但由于我的struct里各种成员都默认初始化了非0值，所以from_pb后得到的东西就不对了。

**Comment by wangwenx190** [comment]
现在我有点不清楚这个算不算是bug了。如果要用户侧规避这个问题，就要求用户那边把各种成员默认初始化成0，如果要这个库解决这个问题，就要在from_pb里把没有找到的字段手动设置成0，而不是直接跳过

**Comment by wangwenx190** [comment]
```cpp
enum MyEnum { AA, BB };
struct MyStruct {
  MyEnum myEnum;
  int myInt;
};
YLT_REFL(MyStruct, myEnum, myInt)

int main() {
  std::string str{};
  MyStruct myStruct1;
  myStruct1.myEnum = MyEnum::AA;
  myStruct1.myInt = 0;
  iguana::to_pb(myStruct1, str);
  MyStruct myStruct2;
  myStruct2.myEnum = MyEnum::BB;
  myStruct2.myInt = 1;
  iguana::from_pb(myStruct2, str);
  return 0;
}
```
请测试这段代码，可以完美复现我的问题。

按理说不论myStruct2之前内容是什么，在from_pb后都应该还原为myStruct1的内容，但实际上由于myStruct1里的成员值都是0，所以str是空的，进而导致from_pb跳过了所有成员的设置。

实际上不需要把所有成员的值都设置成0，现在的结论是from_pb会跳过没有找到的字段，导致最终的结构体不是100%被还原。

**Comment by qicosmos** [comment]
你要看一下protobuf 对于0 是不是也忽略的，印象中protobuf也是忽略0的。
