### ISSUE TITLE
json序列化为文本，有办法prettify吗

### ISSUE THREAD

**Issue by wangwenx190** [qicosmos/iguana#328]
现在iguana输出的json文本都是compat格式那种，全都放到一行的，有没有办法像xml的prettify一样，至少能换行输出？

**Comment by qicosmos** [comment]
有的，就是iguana::prettify 函数。
看这个测试：
https://github.com/qicosmos/iguana/blob/master/test/test_some.cpp#L479

**Comment by wangwenx190** [comment]
好的，太感谢了
