### ISSUE TITLE
结构体字段比json少，反序列化失败

### ISSUE THREAD

**Issue by julinfn** [qicosmos/iguana#34]
需求：只需要解析json里的某些字段，不管json怎么变，只要结构体要求的字段在就能解析。
当前：结构体必须要有json的所有字段。

**Comment by qicosmos** [comment]
是的，这里做了数量检查。

**Comment by julinfn** [comment]
这地方能不能改改啊，这样就省事多了，不然接口返回值改一次就不能用了，在这方面实用性就打折扣了。

**Comment by qicosmos** [comment]
我抽时间改进一下这里，把限定放宽。

**Comment by julinfn** [comment]
恩，解决了吱一声啊，急用。

**Comment by qicosmos** [comment]
已经放宽限制了，不管字段多少，只要有字段就会赋值，你测试一下看看。@julinfn

 remove fields number restriction, more or less field is ok.
I'm not sure it is good or bad, it's up to you

**Comment by julinfn** [comment]
可以了，赞。

**Comment by julinfn** [comment]
遇到问题了，应该是遇到死循环了，然后内存就爆了。
