### ISSUE TITLE
反序列化会陷入死循环的问题？

### ISSUE THREAD

**Issue by anjisZhou** [qicosmos/iguana#35]
`struct A
{
	int a;
	std::string b;
};
struct B
{
	A a;
	std::string c;
};`
REFLECTION(A, a,b);
REFLECTION(B, a,c);

序列化：{"a":{"a":1,"b":"123"},"c":"123"}  json没问题。
但是序列化：{"a":{"a":1},"c":"123"} 会陷入死循环

**Comment by qicosmos** [comment]
iguana是要求两边的元素个数是相同的，不同将返回失败。不过死循环是一个bug，等晚些时候处理了。

**Comment by anjisZhou** [comment]
好的，非常感谢

**Comment by qicosmos** [comment]
更新一下代码看看死循环是不是解决了。@anjisZhou

**Comment by anjisZhou** [comment]
好了，非常感谢。

**Comment by qicosmos** [comment]
如果没问题的话就关闭一下issue

**Comment by anjisZhou** [comment]
好的
