### ISSUE TITLE
反序列化时的问题？

### ISSUE THREAD

**Issue by anjisZhou** [qicosmos/iguana#43]
template<typename T>
        void check_result(T val, char const *str){
            if(val == 0 && strcmp(str,"0") != 0){
                g_has_error = true;
            }
        }
在源代码里面看到有这行代码，序列化std::map<int,自定义结构>时，如果key是0，在某些时候from_json（对象，JSON字符串）会返回false,,但是检查对象时，发现数据都已经反序列化成功。

**Comment by qicosmos** [comment]
能把测试代码发出来吗？

**Comment by anjisZhou** [comment]
`struct MyStruct
{
	std::map<int, std::string>ABC;
};
#define MyStruct_MEMBER  ABC
REFLECTION(MyStruct, MyStruct_MEMBER);
void Test1();
int main()
{
	Test1();
return 0;
}
void Test1()
{
	MyStruct myStruct, myStruct1;
	myStruct.ABC[0] = "123";
	myStruct.ABC[1] = "456";
	myStruct.ABC[2] = "789";

	iguana::string_stream ss;
	iguana::json::to_json(ss, myStruct);
	std::string json = ss.str();
	bool ret = iguana::json::from_json(myStruct, json.data());
}`

**Comment by exat500g** [comment]
出问题时strcmp的输入参数是 0":"123","1":"456","2":"789"}} 和 "0"
strcmp在比较两个不同长度的字符串时不会返回0
修改成这样有副作用吗
```
template<typename T>
void check_result(T val, char const *str){
    std::cout<<"check_result("<<val<<","<<str<<")\r\n";
    if(val == 0 && str && str[0]!='0'){
        g_has_error = true;
    }
}
```

**Comment by qicosmos** [comment]
我晚点看一下。

**Comment by anjisZhou** [comment]
现在好像可以了，非常感谢
