### ISSUE TITLE
How to package as a dynamic library（如何封装成库）

### ISSUE THREAD

**Issue by dbbnsyg001** [qicosmos/iguana#62]
Hi bro, after reading your project, thank you very much for sharing such good things

I have a question:

Because the project is written in xxx.hpp and c++ template

I want to  make package to dll and .h ，but it's too hard.

So I want to ask how to do this 

Thanks !

嗨，兄弟，看完你的项目，非常感谢你分享这么好的东西

我有一个问题:

因为项目是用xxx.hpp和c++模板编写的

我想让它封装为dll和。h，但它太难了。

我想问一下如何做到这一点

谢谢!

**Comment by qicosmos** [comment]
直接包含头文件就行了，不需要搞成dll

**Comment by dbbnsyg001** [comment]
Thanks，i think that's right!
