### ISSUE TITLE
序列化时容器为空时有小问题

### ISSUE THREAD

**Issue by SmallXing** [qicosmos/iguana#7]
容器为空时，序列化时 未做判断

		template<typename InputIt, typename T, typename F>
		T join(InputIt first, InputIt last, const T &delim, const F &f) {
			if (first == last) return T();
			T t = f(*first++);
			while (first != last) {
				t += delim;
				t += f(*first++);
			}
			return t;
		}

		template<typename Stream, typename InputIt, typename T, typename F>
		void join(Stream& ss, InputIt first, InputIt last, const T &delim, const F &f) {
			if (first == last) return;
			f(*first++);
			while (first != last) {
				ss.put(delim);
				f(*first++);
			}
		}

**Comment by qicosmos** [comment]
谢谢支出，已经增加了判断。
