### ISSUE TITLE
build error in CentOS7 env

### ISSUE THREAD

**Issue by savagecm** [qicosmos/iguana#8]
I met build error in my env. Do we have tutorial about how to build this project in Linux env?
my gcc version is 5.30
Build log:
[mcong@localhost build]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc/libexec/gcc/x86_64-unknown-linux-gnu/5.3.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --prefix=/usr/local/gcc --enable-threads=posix --disable-checking --enable-languages=c,c++ --disable-multilib --with-gmp=/usr/local/lib --with-mpfr=/usr/local/lib --with-mpc=/usr/local/lib
Thread model: posix
gcc version 5.3.0 (GCC)
[mcong@localhost build]$ vi /home/mcong/study/github/iguana/reflection.hpp
[mcong@localhost build]$ make
Scanning dependencies of target json_example
[ 33%] Building CXX object CMakeFiles/json_example.dir/example/json_example.cpp.o
In file included from /home/mcong/study/github/iguana/json.hpp:8:0,
                 from /home/mcong/study/github/example/json_example.cpp:1:
/home/mcong/study/github/iguana/reflection.hpp:326:55: error: global qualification of class name is invalid before ‘{’ token
 template<>struct ::iguana_reflect_members<STRUCT_NAME>{\
                                                       ^
/home/mcong/study/github/iguana/reflection.hpp:338:5: note: in expansion of macro ‘MAKE_META_DATA_IMPL’
     MAKE_META_DATA_IMPL(STRUCT_NAME, MAKE_ARG_LIST(N, &STRUCT_NAME::OBJECT, __VA_ARGS__))
     ^
/home/mcong/study/github/iguana/reflection.hpp:343:1: note: in expansion of macro ‘MAKE_META_DATA’
 MAKE_META_DATA(STRUCT_NAME, GET_ARG_COUNT(__VA_ARGS__), __VA_ARGS__)
 ^
/home/mcong/study/github/example/json_example.cpp:11:2: note: in expansion of macro ‘REFLECTION’
  REFLECTION(person, name, age);
  ^
/home/mcong/study/github/example/json_example.cpp: In function ‘int main()’:
/home/mcong/study/github/example/json_example.cpp:19:29: error: no matching function for call to ‘to_json(iguana::string_stream&, client::person&)’
  iguana::json::to_json(ss, p);
                             ^
In file included from /home/mcong/study/github/example/json_example.cpp:1:0:
/home/mcong/study/github/iguana/json.hpp:138:7: note: candidate: template<class Stream, class T> std::enable_if_t<iguana::is_reflection<T>::value> iguana::json::to_json(Stream&, T&&)
  auto to_json(Stream& s, T &&t) -> std::enable_if_t<is_reflection<T>::value>
       ^
/home/mcong/study/github/iguana/json.hpp:138:7: note:   template argument deduction/substitution failed:
/home/mcong/study/github/iguana/json.hpp:161:7: note: candidate: template<class Stream, class T> void iguana::json::to_json(Stream&, const std::vector<T>&)
  void to_json(Stream& s, const std::vector<T> &v) {
       ^
/home/mcong/study/github/iguana/json.hpp:161:7: note:   template argument deduction/substitution failed:
/home/mcong/study/github/example/json_example.cpp:19:29: note:   ‘client::person’ is not derived from ‘const std::vector<T>’
  iguana::json::to_json(ss, p);
                             ^
In file included from /home/mcong/study/github/example/json_example.cpp:1:0:
/home/mcong/study/github/iguana/json.hpp:166:7: note: candidate: template<class Stream, class ... Args> void iguana::json::to_json(Stream&, std::tuple<_Elements ...>)
  void to_json(Stream& s, std::tuple<Args...> tp) {
       ^
/home/mcong/study/github/iguana/json.hpp:166:7: note:   template argument deduction/substitution failed:
/home/mcong/study/github/example/json_example.cpp:19:29: note:   ‘client::person’ is not derived from ‘std::tuple<_Elements ...>’
  iguana::json::to_json(ss, p);
                             ^
/home/mcong/study/github/example/json_example.cpp:25:64: error: no matching function for call to ‘from_json(client::person&, const char*, std::__cxx11::basic_string<char>::size_type)’
  iguana::json::from_json(p2, json_str.data(), json_str.length());
                                                                ^
In file included from /home/mcong/study/github/example/json_example.cpp:1:0:
/home/mcong/study/github/iguana/json.hpp:1030:7: note: candidate: template<class T, class> void iguana::json::from_json(T&&, const char*, size_t)
  void from_json(T &&t, const char *buf, size_t len = -1) {
       ^
/home/mcong/study/github/iguana/json.hpp:1030:7: note:   template argument deduction/substitution failed:
make[2]: *** [CMakeFiles/json_example.dir/example/json_example.cpp.o] Error 1
make[1]: *** [CMakeFiles/json_example.dir/all] Error 2
make: *** [all] Error 2

**Comment by qicosmos** [comment]
@savagecm 你取一下代码再试试，看行不行。

**Comment by qicosmos** [comment]
有问题的话你再打开这个issue吧。
