### ISSUE TITLE
char array problem

### ISSUE THREAD

**Issue by ahao1995** [qicosmos/iguana#84]
hi:
In some cases, I want to use char array in struct, not use std::string, I found it deal char array as c_array,  is there any suggestion to make it like string

**Comment by qicosmos** [comment]
you could use char array in a struct:https://github.com/qicosmos/iguana/blob/master/test/test.cpp#L201

**Comment by qicosmos** [comment]
I think it's has been fixed, can be closed?

**Comment by ahao1995** [comment]
thanks
