### ISSUE TITLE
struct_container_t build faild

### ISSUE THREAD

**Issue by dust-II** [qicosmos/iguana#93]
**compiling environment：ubuntu16.04，gcc 12.1.0**

code is as following:

struct struct_test_t {
	int32_t value;
};
REFLECTION(struct_test_t, value);

struct struct_container_t {
	std::vector<struct_test_t> values;
};
REFLECTION(struct_container_t, values);

  std::string json_str = "123";
  struct_container_t struct_container_obj;
  iguana::from_json(struct_container_obj, std::begin(json_str), std::end(json_str)); //编译失败
  iguana::string_stream ss;
  iguana::json::to_json(ss, struct_container_obj); //可以编译通过

build log is:
[build] /home/zeeuser/workspace/project/github/iguana/iguana/json_reader.hpp:253:15: error: no matching function for call to ‘parse_item(__gnu_cxx::__alloc_traits<std::allocator<struct_test_t>, struct_test_t>::value_type&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&)’
[build]   253 |     parse_item(value.emplace_back(), it, end);
[build]       |     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /home/zeeuser/workspace/project/github/iguana/iguana/json_reader.hpp:144:20: note: candidate: ‘template<class U, class It, class auto:65>  requires  num_t<U> void iguana::parse_item(U&, It&&, auto:65&&)’
[build]   144 | IGUANA_INLINE void parse_item(U &value, It &&it, auto &&end) {
[build]       |                    ^~~~~~~~~~
[build] /home/zeeuser/workspace/project/github/iguana/iguana/json_reader.hpp:144:20: note:   template argument deduction/substitution failed:
[build] /home/zeeuser/workspace/project/github/iguana/iguana/json_reader.hpp:144:20: note: constraints not satisfied
[build] /home/zeeuser/workspace/project/github/iguana/iguana/json_reader.hpp: In substitution of ‘template<class U, class It, class auto:65>  requires  num_t<U> void iguana::parse_item(U&, It&&, auto:65&&) [with U = struct_test_t; It = __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&; auto:65 = __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&]’:
[build] /home/zeeuser/workspace/project/github/iguana/iguana/json_reader.hpp:253:15:   required from ‘void iguana::parse_item(U&, It&&, auto:68&&) [with U = std::vector<struct_test_t>; It = __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&; auto:68 = __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&]’
[build] /home/zeeuser/workspace/project/github/iguana/iguana/json_reader.hpp:441:27:   required from ‘iguana::from_json<struct_container_t, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >(struct_container_t&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&)::<lambda(auto:77&&)> [with auto:77 = std::vector<struct_test_t> struct_container_t::* const&]’
[build] /usr/local/gcc-12.1/include/c++/12.1.0/type_traits:2565:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = iguana::from_json<struct_container_t, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >(struct_container_t&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&)::<lambda(auto:77&&)>; _Args = {std::vector<struct_test_t, std::allocator<struct_test_t> > struct_container_t::* const&}]’
[build] /usr/local/gcc-12.1/include/c++/12.1.0/type_traits:2576:55:   required from ‘struct std::__result_of_impl<false, false, iguana::from_json<struct_container_t, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >(struct_container_t&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&)::<lambda(auto:77&&)>, std::vector<struct_test_t, std::allocator<struct_test_t> > struct_container_t::* const&>’
[build] /usr/local/gcc-12.1/include/c++/12.1.0/type_traits:2581:12:   required from ‘struct std::__invoke_result<iguana::from_json<struct_container_t, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >(struct_container_t&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&)::<lambda(auto:77&&)>, std::vector<struct_test_t, std::allocator<struct_test_t> > struct_container_t::* const&>’
[build] /usr/local/gcc-12.1/include/c++/12.1.0/type_traits:3022:12:   required from ‘struct std::invoke_result<iguana::from_json<struct_container_t, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >(struct_container_t&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&)::<lambda(auto:77&&)>, std::vector<struct_test_t, std::allocator<struct_test_t> > struct_container_t::* const&>’
[build] /usr/local/gcc-12.1/include/c++/12.1.0/type_traits:3034:11:   required by substitution of ‘template<class _Fn, class ... _Args> using invoke_result_t = typename std::invoke_result::type [with _Fn = iguana::from_json<struct_container_t, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >(struct_container_t&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&)::<lambda(auto:77&&)>; _Args = {std::vector<struct_test_t, std::allocator<struct_test_t> > struct_container_t::* const&}]’
[build] /usr/local/gcc-12.1/include/c++/12.1.0/variant:1093:11:   required by substitution of ‘template<class _Visitor, class ... _Variants> using __visit_result_t = std::invoke_result_t<_Visitor, std::__detail::__variant::__get_t<0, _Variants, decltype (std::__detail::__variant::__as(declval<_Variants>())), typename std::variant_alternative<0, typename std::remove_reference<decltype (std::__detail::__variant::__as(declval<_Variants>()))>::type>::type>...> [with _Visitor = iguana::from_json<struct_container_t, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >(struct_container_t&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&)::<lambda(auto:77&&)>; _Variants = {const std::variant<std::vector<struct_test_t, std::allocator<struct_test_t> > struct_container_t::*>&}]’
[build] /usr/local/gcc-12.1/include/c++/12.1.0/variant:1819:5:   required by substitution of ‘template<class _Visitor, class ... _Variants> constexpr std::__detail::__variant::__visit_result_t<_Visitor, _Variants ...> std::visit(_Visitor&&, _Variants&& ...) [with _Visitor = iguana::from_json<struct_container_t, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >(struct_container_t&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >&&)::<lambda(auto:77&&)>; _Variants = {const std::variant<std::vector<struct_test_t, std::allocator<struct_test_t> > struct_container_t::*>&}]’
[build] /home/zeeuser/workspace/project/github/iguana/iguana/json_reader.hpp:437:19:   required from ‘void iguana::from_json(T&, It&&, It&&) [with T = struct_container_t; It = __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >]’
[build] /home/zeeuser/workspace/project/github/iguana/test/json_file_test.cpp:32:20:   required from here

**Comment by qicosmos** [comment]
update to the latest code, no error in the latest code.

**Comment by dust-II** [comment]
//branch is master, gcc12.1.0

struct struct_test_t {
	int32_t value;
};
REFLECTION(struct_test_t, value);

struct struct_container_t {
	std::vector<struct_test_t> values;
};
REFLECTION(struct_container_t, values);

struct struct_container_1_t {
	std::optional<struct_container_t> val;
}; // entities_t
REFLECTION(struct_container_1_t, val);

**Comment by dust-II** [comment]
seems can fixed by this way:
        if constexpr (refletable<typename T::value_type>) {
          from_json(t, it, end);  
        } else {
          parse_item(t, it, end);
        }
I will try to understand the code...

**Comment by qicosmos** [comment]
yes, has been fixed.
https://github.com/qicosmos/iguana/blob/master/test/unit_test.cpp#L356

**Comment by dust-II** [comment]
//struct for twitter.json, without namespace. After passed, need test namepace/class

//namespace TwitterBase {
  using twitter_tp = std::string;  //std::chrono::time_point<std::chrono::system_clock,
	                    //                       std::chrono::milliseconds>;
	struct metadata_t {
		std::string result_type;
		std::string iso_language_code;
	};
	REFLECTION(metadata_t, result_type, iso_language_code);

	struct urls_element_t {
		std::string url;
		std::string expanded_url;
		std::string display_url;
		std::vector<int32_t> indices;
	};
	REFLECTION(urls_element_t, url, expanded_url, display_url, indices);

	struct url_t {
		std::vector<urls_element_t> urls;
	};
	REFLECTION(url_t, urls);

	struct entities_t {
		std::optional<url_t> url;
		std::optional<url_t> description;
	}; // entities_t
	REFLECTION(entities_t, url, description);

	struct user_t {
		int64_t id;
		std::string id_str;
		std::string name;
		std::string screen_name;
		std::string location;
		std::string description;
		std::optional<std::string> url;
		entities_t entities;
		bool _jsonprotected;
		int32_t followers_count;
		int32_t friends_count;
		int32_t listed_count;
		twitter_tp created_at;
		int32_t favourites_count;
		bool geo_enabled;
		bool verified;
		int32_t statuses_count;
		std::string lang;
		bool contributors_enabled;
		bool is_translator;
		bool is_translation_enabled;
		std::string profile_background_color;
		std::string profile_background_image_url;
		std::string profile_background_image_url_https;
		bool profile_background_tile;
		std::string profile_image_url;
		std::string profile_image_url_https;
		std::optional<std::string> profile_banner_url;
		std::string profile_link_color;
		std::string profile_sidebar_border_color;
		std::string profile_sidebar_fill_color;
		std::string profile_text_color;
		bool profile_use_background_image;
		bool default_profile;
		bool default_profile_image;
		bool following;
		bool follow_request_sent;
		bool notifications;
	}; // user_t
	REFLECTION(user_t, id, id_str, name, screen_name, location, description, url, entities, _jsonprotected,
					   followers_count, friends_count, listed_count, created_at, favourites_count, geo_enabled,
					   verified, statuses_count, lang, contributors_enabled, is_translator, is_translation_enabled,
					   profile_background_color, profile_background_image_url, profile_background_image_url_https,
					   profile_background_tile, profile_image_url, profile_image_url_https, profile_banner_url,
					   profile_link_color, profile_sidebar_border_color, profile_sidebar_fill_color,
					   profile_text_color, profile_use_background_image, default_profile,
					   default_profile_image, following, follow_request_sent, notifications);

	struct hashtags_element_t {
		std::string text;
		std::vector<int32_t> indices;
	}; // hashtags_element_t
	REFLECTION(hashtags_element_t, text, indices);

	struct tweet_object_t {
		metadata_t metadata;
		twitter_tp created_at;
		int64_t id;
		std::string id_str;
		std::string text;
		std::string source;
		bool truncated;
		std::optional<int64_t> in_reply_to_status_id;
		std::optional<std::string> in_reply_to_status_id_str;
		std::optional<int64_t> in_reply_to_user_id;
		std::optional<std::string> in_reply_to_user_id_str;
		std::optional<std::string> in_reply_to_screen_name;
		user_t user;
		int32_t retweet_count;
		std::optional<int32_t> favorite_count;
		entities_t entities;
		bool favorited;
		bool retweeted;
		std::optional<bool> possibly_sensitive;
		std::string lang;
	}; // statuses_element_t
	REFLECTION(tweet_object_t, metadata, created_at, id, id_str, text, source, truncated, 
						       in_reply_to_status_id, in_reply_to_status_id_str, in_reply_to_user_id, 
							   in_reply_to_user_id_str, in_reply_to_screen_name, user, retweet_count, 
							   favorite_count, entities, favorited, retweeted,possibly_sensitive, lang);

	struct user_mentions_element_t {
		std::string screen_name;
		std::string name;
		int64_t id;
		std::string id_str;
		std::vector<int32_t> indices;
	}; // user_mentions_element_t
	REFLECTION(user_mentions_element_t, screen_name, name, id, id_str, indices);

	struct size_item_t {
		int64_t w;
		int64_t h;
		std::string resize;
	}; // size_item_t
	REFLECTION(size_item_t, w, h, resize);

	struct sizes_t {
		size_item_t medium;
		size_item_t small_;
		size_item_t thumb;
		size_item_t large;
	}; // sizes_t
	REFLECTION(sizes_t, medium, small_, thumb, large);

	struct media_element_t {
		int64_t id;
		std::string id_str;
		std::vector<int32_t> indices;
		std::string media_url;
		std::string media_url_https;
		std::string url;
		std::string display_url;
		std::string expanded_url;
		std::string type;
		sizes_t sizes;
	}; // media_element_t
	REFLECTION(media_element_t, id, id_str, indices, media_url, media_url_https, url, display_url, expanded_url, type, sizes);

	struct retweeted_status_t {
		metadata_t metadata;
		twitter_tp created_at;
		int64_t id;
		std::string id_str;
		std::string text;
		std::string source;
		bool truncated;
		std::optional<int64_t> in_reply_to_status_id;
		std::optional<std::string> in_reply_to_status_id_str;
		std::optional<int64_t> in_reply_to_user_id;
		std::optional<std::string> in_reply_to_user_id_str;
		std::optional<std::string> in_reply_to_screen_name;
		user_t user;
		int32_t retweet_count;
		std::optional<int32_t> favorite_count;
		entities_t entities;
		bool favorited;
		bool retweeted;
		std::optional<bool> possibly_sensitive;
		std::string lang;
	}; // retweeted_status_t
	REFLECTION(retweeted_status_t, metadata, created_at, id, id_str, text, source, truncated, in_reply_to_status_id,
								   in_reply_to_status_id_str, in_reply_to_user_id, in_reply_to_user_id_str,
								   in_reply_to_screen_name, user, retweet_count, favorite_count, entities, favorited, 
								   retweeted, possibly_sensitive, lang);

	struct search_metadata_t {
		double completed_in;
		int64_t max_id;
		std::string max_id_str;
		std::string next_results;
		std::string query;
		std::string refresh_url;
		int64_t count;
		int64_t since_id;
		std::string since_id_str;
	}; // search_metadata_t
	REFLECTION(search_metadata_t, completed_in, max_id, max_id_str, next_results, query,
	                              refresh_url, count, since_id, since_id_str);

	struct twitter_object_t {
		std::vector<tweet_object_t> statuses;
		search_metadata_t search_metadata;
	};
	REFLECTION(twitter_object_t, statuses, search_metadata);
    /* data */
//};

**Comment by qicosmos** [comment]
I think it's has been fixed, can be closed?
